version: "3.8"
services:
    backend:
        build:
            context: ./
        ports:
            - "4000:4000"

    nginx:
        restart: always
        build:
            context: ./nginx
        ports:
            - "80:80"